In [2]:
import numpy as np

In [4]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.concatenate((arr1,arr2))
print(arr)

[10 20 30 40]

[1 2 3 4]
[10 20 30 40  1  2  3  4]


In [5]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[100,200,300],[400,500,600]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]
 [400 500 600]]


In [20]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[10 20 30 40]

[1 2 3 4]
[[10  1]
 [20  2]
 [30  3]
 [40  4]]


In [11]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[100,200,300],[400,500,600]])
print(arr1)
print()
print(arr2)
arr=np.stack((arr1,arr2),axis=2)
print(arr)

[[10 20 30]
 [40 50 60]]

[[100 200 300]
 [400 500 600]]
[[[ 10 100]
  [ 20 200]
  [ 30 300]]

 [[ 40 400]
  [ 50 500]
  [ 60 600]]]


In [14]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2=np.array([[100,200,300],[400,500,600],[700,800,900]])
print(arr1)
print()
print(arr2)
arr=np.stack((arr1,arr2),axis=2)
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[[ 10 100]
  [ 20 200]
  [ 30 300]]

 [[ 40 400]
  [ 50 500]
  [ 60 600]]

 [[ 70 700]
  [ 80 800]
  [ 90 900]]]


In [16]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.vstack((arr1,arr2))
print(arr)

[10 20 30 40]

[1 2 3 4]
[[10 20 30 40]
 [ 1  2  3  4]]


In [17]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.hstack((arr1,arr2))
print(arr)

[10 20 30 40]

[1 2 3 4]
[10 20 30 40  1  2  3  4]


In [18]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print()
print(arr2)
arr=np.dstack((arr1,arr2))
print(arr)

[10 20 30 40]

[1 2 3 4]
[[[10  1]
  [20  2]
  [30  3]
  [40  4]]]


In [21]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[100,200,300],[400,500,600]])
print(arr1)
print()
print(arr2)
arr=np.vstack((arr1,arr2))
print(arr)

[[10 20 30]
 [40 50 60]]

[[100 200 300]
 [400 500 600]]
[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]
 [400 500 600]]


In [23]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[100,200,300],[400,500,600]])
print(arr1)
print()
print(arr2)
arr=np.hstack((arr1,arr2))
print(arr)

[[10 20 30]
 [40 50 60]]

[[100 200 300]
 [400 500 600]]
[[ 10  20  30 100 200 300]
 [ 40  50  60 400 500 600]]


In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=np.split(arr,3)
print(arr1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=np.split(arr,3)
print(arr1)
for i in arr1:
    print(i)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


In [30]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=np.array_split(arr,2)
print(arr1)
for i in arr1:
    print(i)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]
[1 2 3 4 5]
[6 7 8 9]
