In [1]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
int64
(5,)
5


In [8]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [10]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
3
(3, 3, 3)
27
int64


In [14]:
# arange(start,stop,step)
# it always return single dimension array
arr=np.arange(10)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
10
int64


In [24]:
arr=np.arange(1,13)
print(arr)
arr1=arr.reshape(4,3)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
arr=np.arange(1,28).reshape(3,1,9)
print(arr)

[[[ 1  2  3  4  5  6  7  8  9]]

 [[10 11 12 13 14 15 16 17 18]]

 [[19 20 21 22 23 24 25 26 27]]]


In [29]:
# indexing
arr=np.arange(1,9)
print(arr)
print(arr[-1])

[1 2 3 4 5 6 7 8]
8


In [32]:
arr=np.arange(1,9).reshape(2,4)
print(arr)
print(arr[0][-1])

[[1 2 3 4]
 [5 6 7 8]]
4


In [36]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print(arr[1][2][2])
print(arr[1][2][1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
18
17


In [39]:
# iteration
arr=np.array([10,20,30,40,50])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [41]:
arr=np.array([10,20,30,40,50])
print(arr)
for i in range(len(arr)):
    print(i,arr[i])

[10 20 30 40 50]
0 10
1 20
2 30
3 40
4 50


In [44]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
for i in arr:
    for j in i:
        print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30
40
50
60
70
80
90


In [48]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i in arr:
    for j in i:
        for k in j:
            print(k,end=" ")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [50]:
# np.nditer()
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i in np.nditer(arr):
    print(i,end=" ")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [52]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i,j in np.ndenumerate(arr):
    print(i,j)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 2, 0) 16
(1, 2, 1) 17
(1, 2, 2) 18


In [1]:
#special filled array 
# zeros
import numpy as np
arr=np.zeros(4)
print(arr)


[0. 0. 0. 0.]


In [2]:
arr=np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
arr=np.zeros((3,3,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
#ones()
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [5]:
arr=np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
arr=np.ones((2,4,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
#eye 
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr=np.eye(4)
print(arr)
print(arr[::-1])


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [9]:
arr=np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [14]:
#evenly spaced array 
# linspace (start,stop,count)
#both start and stop are inclusive
arr=np.linspace(2,10,5)
print(arr)

[ 2.  4.  6.  8. 10.]


In [19]:
#random rand function 
#range is btw 0 and 1
#0 is inclusive but 1 is not inclusive
arr=np.random.rand(8)
print(arr)

[0.43094112 0.98889964 0.215692   0.48795674 0.57098121 0.92841531
 0.41760893 0.23123685]


In [20]:
arr=np.random.randn(5)
print(arr)

[ 0.45549814 -0.34523142  0.20066444 -0.37425341 -0.96881141]


In [21]:
arr=np.random.randint(20,40,(100))
print(arr)

[39 31 20 24 36 28 31 24 24 32 24 28 21 26 24 39 29 36 27 38 29 23 25 22
 25 34 31 33 24 25 28 37 27 31 31 25 21 39 33 20 37 38 39 24 38 22 24 35
 32 26 28 22 23 29 33 37 39 39 21 38 21 36 20 29 25 25 25 31 32 22 39 34
 32 22 24 32 25 32 34 27 23 34 23 23 25 32 34 23 34 39 29 27 26 21 21 28
 31 34 23 22]


In [7]:
import numpy as np
arr=np.random.rand(30)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[0.291718   0.73367655 0.17120407 0.34719606 0.45347619 0.91654711
 0.1380581  0.01116859 0.84583125 0.25956327 0.30437335 0.62589688
 0.6903882  0.45724208 0.1577989  0.29323629 0.50780455 0.0110211
 0.1215124  0.5257804  0.93978151 0.34250813 0.10489604 0.96325255
 0.66451511 0.25501689 0.57272473 0.12348801 0.56456743 0.01887876]
<class 'numpy.ndarray'>
1
(30,)
30
float64


In [6]:
arr=np.arange(0, 30) 
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>
1
(30,)
30
int64


In [8]:
arr = np.linspace(21, 30, 30)
print(arr)

[21.         21.31034483 21.62068966 21.93103448 22.24137931 22.55172414
 22.86206897 23.17241379 23.48275862 23.79310345 24.10344828 24.4137931
 24.72413793 25.03448276 25.34482759 25.65517241 25.96551724 26.27586207
 26.5862069  26.89655172 27.20689655 27.51724138 27.82758621 28.13793103
 28.44827586 28.75862069 29.06896552 29.37931034 29.68965517 30.        ]
