In [3]:
import numpy as np


## datatype

In [2]:
#datatype
arr=np.array([10,20,30,40],dtype="str")
print(arr)
print(arr.dtype)

['10' '20' '30' '40']
<U2


In [5]:
arr=np.array([10.0,20.0,30.0,40.0])
print(arr)
print(arr.dtype)

[10. 20. 30. 40.]
float64


In [6]:
arr1=arr.astype("int")
print(arr1)

[10 20 30 40]


In [7]:
#copy vs view 
arr=np.array([10,20,30,40,50])
print(arr)
c=arr.copy()
print(c)
c[2]=100
print(c)
print(arr)

[10 20 30 40 50]
[10 20 30 40 50]
[ 10  20 100  40  50]
[10 20 30 40 50]


In [8]:
arr=np.array([10,20,30,40,50])
print(arr)
v=arr.view()
print(v)
v[2]=1000
print(v)
print(arr)

[10 20 30 40 50]
[10 20 30 40 50]
[  10   20 1000   40   50]
[  10   20 1000   40   50]


## reshape 

In [9]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr=np.arange(1,10)
print(arr)
print(arr[::-1])
print(arr[2::2])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[3 5 7 9]


In [17]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
print()
print(arr[::-1])
print()
print(arr[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [16]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print()
print(arr[::-1,::-1,::-1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[27 26 25]
  [24 23 22]
  [21 20 19]]

 [[18 17 16]
  [15 14 13]
  [12 11 10]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]


## arithmetic array

In [18]:
#arithmetic 
arr=np.array([10,20,30,40])
print(arr)
arr1=arr+8
print(arr1)
arr2=np.add(arr1,8)
print(arr2)

             

[10 20 30 40]
[18 28 38 48]
[26 36 46 56]


In [20]:
arr=np.array([10,20,30,40])
print(arr)
arr_new=arr-8
print(arr_new)
arr_new1=np.subtract(arr_new,2)
print(arr_new1)


[10 20 30 40]
[ 2 12 22 32]
[ 0 10 20 30]


In [21]:
arr=np.array([1,2,3,4])
print(arr)
arr1=1/arr
print(arr1)
arr2=np.reciprocal(arr)
print(arr2)

[1 2 3 4]
[1.         0.5        0.33333333 0.25      ]
[1 0 0 0]


In [33]:
arr=np.array([1,2,3,4])
print(arr)
arr_1=1%arr
print(arr_1)
arr3=np.remainder(1,arr)  #modulus
print(arr3)

[1 2 3 4]
[0 1 1 1]
[0 1 1 1]


In [4]:
arr=np.array([1,2,3,4])
print(arr)
arr_1=1%arr
print(arr_1)
arr3=np.mod(arr,2)  #modulus
print(arr3)

[1 2 3 4]
[0 1 1 1]
[1 0 1 0]


In [35]:
arr=np.array([1,2,3,4])
print(arr)
arr_p=arr**1
print(arr_p)
arr_power=np.power(arr,1)
print(arr_power)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
