# broadcasting

In [ ]:
#broadcasting is a powerful technique that allow aethmetic operation to perform on array 
#on diffrent shapes it streches the smaller array so that it has the same shape as the larger one 
#, enables elements wise operation . the core rule of broadcasting 
#if 2 array are compalible 
#compare the dim 
#starting trailing dim 
# 2 dim are compilable if they are equal or one of them is one 
#if the condition are not mat the numpy throwns type error

In [1]:
import numpy as np

In [5]:
arr1=np.array([10,20,30])
arr2=np.array([10,20,30])
arr=arr1+arr2
print(arr)

[20 40 60]


In [6]:
arr1=np.array([10,20,30])
arr=arr1+4
print(arr)

[14 24 34]


In [8]:
arr1=np.array([10,20,30,40])
arr2=np.array([[1],[2],[3],[4]])
arr=arr1+arr2
print(arr)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]]


In [9]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3])
arr=arr1+arr2
print(arr) #error

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([2,2,2])
arr=arr1+arr2
print(arr)

[[3 4 5]
 [6 7 8]]


In [13]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([2,2,2])
arr=arr1+arr2
print(arr)      # error

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [24]:
# create one random value array having 20 value 
import numpy as np
arr=np.random.randint(1,20,20)
print(arr)

[18  5 14 12  6 19 15 11  1 18 10  2  5 10 13 16  5  1 11 13]


In [19]:
# create one linear space array having 10 values and the space btw is 5 
arr=np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [21]:
# create one array with the help of arrange func having 12 values and reshape that 
# into 2 or 3 dim with all posible dim 
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
