In [1]:
import numpy as np

In [3]:
arr=np.array([10,2,3,16,17,19,98,1])
print(arr)
print(np.max(arr))
print(np.argmax(arr))

[10  2  3 16 17 19 98  1]
98
6


In [4]:
arr=np.array([10,2,3,-10,16,17,19,98,1])
print(arr)
print(np.min(arr))
print(np.argmin(arr))

[ 10   2   3 -10  16  17  19  98   1]
-10
3


In [6]:
arr=np.array([1,4,9,16,25])
print(arr)
print(np.sqrt(arr))

[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]


In [7]:
arr=np.array([1,4,9,16,25])
print(arr)
print(np.cumsum(arr))

[ 1  4  9 16 25]
[ 1  5 14 30 55]


In [32]:
arr=np.array([10,1,34,23,19,3,18])
print(arr)
print(np.sort(arr))

[10  1 34 23 19  3 18]
[ 1  3 10 18 19 23 34]


In [39]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print(np.max(arr))
print(np.argmax(arr))
print(np.max(arr,axis=0))
print(np.argmax(arr,axis=0))
print(np.max(arr,axis=1))
print(np.argmax(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]
98
2
[12 34 98 78]
[1 1 0 1]
[98 78]
[2 3]


In [40]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print(np.min(arr))
print(np.argmin(arr))
print(np.min(arr,axis=0))
print(np.argmin(arr,axis=0))
print(np.min(arr,axis=1))
print(np.argmin(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]
1
1
[10  1 23 56]
[0 0 1 0]
[ 1 12]
[1 0]


In [47]:
arr=np.array([[10,1,16,56],[12,25,23,78]])
print(arr)
print(np.sqrt(arr))

[[10  1 16 56]
 [12 25 23 78]]
[[3.16227766 1.         4.         7.48331477]
 [3.46410162 5.         4.79583152 8.83176087]]


In [50]:
arr=np.array([[10,1,98,56],[12,34,23,78]])
print(arr)
print()
print(np.cumsum(arr))
print()
print(np.cumsum(arr,axis=0))
print()
print(np.cumsum(arr,axis=1))

[[10  1 98 56]
 [12 34 23 78]]

[ 10  11 109 165 177 211 234 312]

[[ 10   1  98  56]
 [ 22  35 121 134]]

[[ 10  11 109 165]
 [ 12  46  69 147]]


In [60]:
arr=np.array([[10,11,78,23],[13,4,156,98]])
print(arr)
print()
print(np.sort(arr))
print()
print(np.sort(arr,axis=0))
print()
print(np.sort(arr,axis=1))

[[ 10  11  78  23]
 [ 13   4 156  98]]

[[ 10  11  23  78]
 [  4  13  98 156]]

[[ 10   4  78  23]
 [ 13  11 156  98]]

[[ 10  11  23  78]
 [  4  13  98 156]]


In [62]:
# max() , min() , sort()
arr=np.array([10,78,1,98,17])
print(arr)
max_value=arr[0]
for i in arr:
    if i>max_value:
        max_value=i
print(max_value)

[10 78  1 98 17]
98


In [63]:
arr=np.array([10,78,1,98,17])
print(arr)
min_value=arr[0]
for i in arr:
    if i<min_value:
        min_value=i
print(min_value)

[10 78  1 98 17]
1


In [64]:
arr=np.array([10,78,1,98,17])
print(arr)
for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]>arr[j]:
            arr[i],arr[j]=arr[j],arr[i]
print(arr)

[10 78  1 98 17]
[ 1 10 17 78 98]
